LANGMAP = {
    "English": "en",
    "Cebuano": "ceb",
    "Swedish": "sv",
    "German": "de",
    "French": "fr",
    "Dutch": "nl",
    "Russian": "ru",
    "Italian": "it",
    "Spanish": "es",
    "Polish": "pl",
    "Waray-Waray": "war",
    "Vietnamese": "vi",
    "Japanese": "ja",
    "Chinese": "zh",
    "Portuguese": "pt",
    "Ukrainian": "uk",
    "Arabic": "ar",
    "Persian": "fa",
    "Serbian": "sr",
    "Catalan": "ca",
    "Indonesian": "id",
    "Finnish": "fi",
    "Korean": "ko",
    "Hungarian": "hu",
    "Serbo-Croatian": "sh",
    "Czech": "cs",
    "Romanian": "ro",
    "Basque": "eu",
    "Turkish": "tr",
    "Malay": "ms",
    "Esperanto": "eo",
    "Bulgarian": "bg",
    "Danish": "da",
    "Armenian": "hy",
    "Hebrew": "he",
    "Slovak": "sk",
    "Min Nan": "zh-min-nan",
    "Min": "zh-min-nan",
    "Kazakh": "kk",
    "Minangkabau": "min",
    "Chechen": "ce",
    "Croatian": "hr",
    "Lithuanian": "lt",
    "Estonian": "et",
    "Belarusian": "be",
    "Slovenian": "sl",
    "Slovene": "sl",
    "Greek": "el",
    "Galician": "gl",
    "Azerbaijani": "az",
    "Azeri": "az",  # For some reason pages like https://stats.wikimedia.org/archive/squid_reports/2018-01/SquidReportPageViewsPerCountryBreakdownHuge.htm use "Azeri" instead of "Azerbaijani" but these seem to be the same thing https://en.wikipedia.org/wiki/Azeri_(disambiguation)
    "Urdu": "ur",
    "Simple English": "simple",
    "Simple": "simple",
    "Norwegian (Nynorsk)": "nn",
    "Nynorsk": "nn",
    "Norwegian (Bokmål)": "no",
    "Norwegian": "no",  # Pages like https://stats.wikimedia.org/archive/squid_reports/2018-01/SquidReportPageViewsPerCountryBreakdownHuge.htm just say "Norwegian" without clarifying whether it's Bokmal or Nynorsk or both. However Nynorsk is listed separately, so I assume this is Bokmal.
    "South Azerbaijani": "azb",
    "Uzbek": "uz",
    "Thai": "th",
    "Hindi": "hi",
    "Latin": "la",
    "Georgian": "ka",
    "Volapük": "vo",
    "Tamil": "ta",
    "Welsh": "cy",
    "Macedonian": "mk",
    "Asturian": "ast",
    "Tajik": "tg",
    "Latvian": "lv",
    "Malagasy": "mg",
    "Occitan": "oc",
    "Tatar": "tt",
    "Bosnian": "bs",
    "Kirghiz": "ky",
    "Kyrghyz": "ky",
    "Afrikaans": "af",
    "Albanian": "sq",
    "Tagalog": "tl",
    "Cantonese": "zh-yue",
    "Newar": "new",
    "Nepal Bhasa": "new",
    "Telugu": "te",
    "Bengali": "bn",
    "Belarusian (Taraškievica)": "be-tarask",
    "be-tarask": "be-tarask",
    "Breton": "br",
    "Piedmontese": "pms",
    "Malayalam": "ml",
    "Luxembourgish": "lb",
    "Javanese": "jv",
    "Haitian": "ht",
    "Scots": "sco",
    "Marathi": "mr",
    "Irish": "ga",
    "Swahili": "sw",
    "Bashkir": "ba",
    "Low Saxon": "nds",
    "Western Punjabi": "pnb",
    "Western Panjabi": "pnb",
    "Western": "pnb",
    "Icelandic": "is",
    "Burmese": "my",
    "West Frisian": "fy",
    "Frisian": "fy",
    "Chuvash": "cv",
    "Sundanese": "su",
    "Lombard": "lmo",
    "Aragonese": "an",
    "Nepali": "ne",
    "Yoruba": "yo",
    "Punjabi": "pa",
    "Gujarati": "gu",
    "Ido": "io",
    "Bavarian": "bar",
    "Sicilian": "scn",
    "Kurdish": "ku",
    "Alemannic": "als",
    "Bishnupriya Manipuri": "bpy",
    "Kannada": "kn",
    "Sorani": "ckb",
    "Interlingua": "ia",
    "Quechua": "qu",
    "Egyptian Arabic": "arz",
    "Egyptian": "arz",
    "Wu": "wuu",
    "Mongolian": "mn",
    "Samogitian": "bat-smg",
    "Sinhalese": "si",
    "Sinhala": "si",
    "Walloon": "wa",
    "Oriya": "or",
    "Scottish Gaelic": "gd",
    "Yiddish": "yi",
    "Amharic": "am",
    "Neapolitan": "nap",
    "Min Dong": "cdo",
    "Buginese": "bug",
    "Upper Sorbian": "hsb",
    "Banyumasan": "map-bms",
    "Maithili": "mai",
    "mai": "mai",
    "Mingrelian": "xmf",
    "xmf": "xmf",
    "Faroese": "fo",
    "Mazandarani": "mzn",
    "Limburgish": "li",
    "Ilokano": "ilo",
    "Sakha": "sah",
    "Emilian-Romagnol": "eml",
    "Venetian": "vec",
    "Ossetian": "os",
    "Sanskrit": "sa",
    "Sindhi": "sd",
    "Hill Mari": "mrj",
    "Zazaki": "diq",
    "Meadow Mari": "mhr",
    "Eastern Mari": "mhr",
    "Pashto": "ps",
    "Fiji Hindi": "hif",
    "Tarantino": "roa-tara",
    "Classical Chinese": "zh-classical",
    "Central Bicolano": "bcl",
    "Acehnese": "ace",
    "Hakka": "hak",
    "North Frisian": "frr",
    "frr": "frr",
    "Kapampangan": "pam",
    "Silesian": "szl",
    "Northern Sotho": "nso",
    "Northern Sami": "se",
    "Khmer": "km",
    "Navajo": "nv",
    "Western Armenian": "hyw",
    "Maori": "mi",
    "Rusyn": "rue",
    "rue": "rue",
    "Nahuatl": "nah",
    "Dutch Low Saxon": "nds-nl",
    "West Flemish": "vls",
    "Bihari": "bh",
    "Crimean Tatar": "crh",
    "Gan": "gan",
    "Sardinian": "sc",
    "Vepsian": "vep",
    "Tibetan": "bo",
    "Gilaki": "glk",
    "Corsican": "co",
    "Erzya": "myv",
    "Turkmen": "tk",
    "Võro": "fiu-vro",
    "Assamese": "as",
    "Somali": "so",
    "Northern Luri": "lrc",
    "Komi": "kv",
    "Kashubian": "csb",
    "Cashubian": "csb",
    "Manx": "gv",
    "Shan": "shn",
    "Udmurt": "udm",
    "Zeelandic": "zea",
    "Zealandic": "zea",
    "Interlingue": "ie",
    "Picard": "pcd",
    "pcd": "pcd",
    "Aymara": "ay",
    "Shona": "sn",
    "Uyghur": "ug",
    "Uighur": "ug",
    "Norman": "nrm",
    "Saterland Frisian": "stq",
    "Lezgian": "lez",
    "lez": "lez",
    "Ladino": "lad",
    "Cornish": "kw",
    "Mirandese": "mwl",
    "Goan Konkani": "gom",
    "gom": "gom",
    "Guarani": "gn",
    "Hawaiian": "haw",
    "Romansh": "rm",
    "Ligurian": "lij",
    "Hausa": "ha",
    "Abkhazian": "ab",
    "Komi-Permyak": "koi",
    "koi": "koi",
    "Kabyle": "kab",
    "Maltese": "mt",
    "Lao": "lo",
    "Laotian": "lo",
    "Lingua Franca Nova": "lfn",
    "Friulian": "fur",
    "Franco-Provençal": "frp",
    "Lower Sorbian": "dsb",
    "Lingala": "ln",
    "Anglo-Saxon": "ang",
    "Extremaduran": "ext",
    "Livvi-Karelian": "olo",
    "Zamboanga Chavacano": "cbk-zam",
    "Doteli": "dty",
    "Divehi": "dv",
    "Ripuarian": "ksh",
    "Gagauz": "gag",
    "gag": "gag",
    "Pali": "pi",
    "Pangasinan": "pag",
    "Palatinate German": "pfl",
    "Avar": "av",
    "Banjar": "bjn",
    "bjn": "bjn",
    "Buryat": "bxr",
    "Kalmyk": "xal",
    "Gorontalo": "gor",
    "Karachay-Balkar": "krc",
    "krc": "krc",
    "Papiamentu": "pap",
    "Zhuang": "za",
    "Karakalpak": "kaa",
    "Pennsylvania German": "pdc",
    "Kinyarwanda": "rw",
    "Tuvan": "tyv",
    "Tongan": "to",
    "Greenlandic": "kl",
    "Novial": "nov",
    "Jamaican Patois": "jam",
    "Aramaic": "arc",
    "Kabiye": "kbp",
    "Kabardian Circassian": "kbd",
    "Tok Pisin": "tpi",
    "Tetum": "tet",
    "Igbo": "ig",
    "Kikuyu": "ki",
    "Nauruan": "na",
    "Lojban": "jbo",
    "Lak": "lbe",
    "Aromanian": "roa-rup",
    "Tahitian": "ty",
    "Bislama": "bi",
    "Kongo": "kg",
    "Moksha": "mdf",
    "Wolof": "wo",
    "Luganda": "lg",
    "Ganda": "lg",
    "Zulu": "zu",
    "Sranan": "srn",
    "Tulu": "tcy",
    "Ingush": "inh",
    "Atikamekw": "atj",
    "Cherokee": "chr",
    "Latgalian": "ltg",
    "ltg": "ltg",
    "Samoan": "sm",
    "Xhosa": "xh",
    "Oromo": "om",
    "Santali": "sat",
    "Norfolk": "pih",
    "Old Church Slavonic": "cu",
    "Romani": "rmy",
    "Twi": "tw",
    "Bambara": "bm",
    "Tswana": "tn",
    "Setswana": "tn",
    "Cheyenne": "chy",
    "Kirundi": "rn",
    "Gothic": "got",
    "Tsonga": "ts",
    "Tumbuka": "tum",
    "Akan": "ak",
    "Sesotho": "st",
    "Chichewa": "ny",
    "Chamorro": "ch",
    "Swati": "ss",
    "Siswati": "ss",
    "Pontic": "pnt",
    "Fijian": "fj",
    "Inuktitut": "iu",
    "Adyghe": "ady",
    "Ewe": "ee",
    "Kashmiri": "ks",
    "Venda": "ve",
    "Inupiak": "ik",
    "Sango": "sg",
    "Sangro": "sg",  # This shows up in 2017-09; I think it's a typo
    "Fula": "ff",
    "Dzongkha": "dz",
    "Tigrinya": "ti",
    "Cree": "cr",
    "Dinka": "din",
    "Ndonga": "ng",
    "Choctaw": "cho",
    "Kuanyama": "kj",
    "Marshallese": "mh",
    "Hiri Motu": "ho",
    "Sichuan Yi": "ii",
    "Afar": "aa",
    "Muscogee": "mus",
    "Herero": "hz",
    "Kanuri": "kr",
    "Low": "nds",  # This page (https://stats.wikimedia.org/wikimedia/squids/SquidReportPageViewsPerLanguageBreakdown.htm) indicates that "Low" is Low Saxon
    "ten": "en", # ten.wikipedia.org was a temporary wiki for the 10-year anniversary of Wikipedia. For ease, I will count the views on this under English Wikipedia
    "nb": "no", # Verified that nb.wikipedia.org redirects to no.wikipedia.org
    "zh-tw": "zh", # Verified that zh-tw.wikipedia.org redirects to zh.wikipedia.org; see also https://en.wikipedia.org/wiki/Chinese_Wikipedia#Automatic_conversion_between_traditional_and_simplified_Chinese_characters
}
